### ISSUE TITLE
docker-compose build fails: Error: pg_config executable not found

### ISSUE THREAD

**Issue by iarspider** [spack/spack-monitor#42]
When building spack-monitor docker image from `main` (commit eb486c92296f80de80859b33261e53561cb3c7cc),
it fails with the following error: `#9 66.71   Error: pg_config executable not found.` (full error here: https://gist.github.com/iarspider/9fcf3fba03b308b7ff5ed12863781f57)

I have checked the psycopg2 [bug tracker](https://github.com/psycopg/psycopg2/issues?q=is%3Aissue+psycopg2-binary+), and all tickets with this error are attributed to old pip version (which is not the case here). I have "fixed" the error by adding `libpq-dev` and `libc-dev` to the image. The latter can be removed after installing python module, but the former (or, at least, `libpq5`) must stay.

**Comment by iarspider** [comment]
The reason it tries to build from source is because there is no wheel for `psycopg2-binary==2.8.5` and Python 3.9

**Comment by vsoch** [comment]
huh, strange that I haven't seen that for my automated image build (although I suppose it could have popped up in the last 30 days). Would you care to PR with the fix? Note here is the last run of the automated build:

https://github.com/spack/spack-monitor/runs/4156272314?check_suite_focus=true

And also note there are bugs in the current version of spack so that no all monitor results are captured in the case of failing builds - someone changed installer.py without accounting for spack monitor it seems. I have fixes in one of my branches here https://github.com/vsoch/spack/tree/vsoch/db-17-splice if you care to cherry pick for a PR to spack.

**Comment by iarspider** [comment]
Sure: https://github.com/spack/spack-monitor/pull/43
Notice that the CI build failed, and this is the same error I observe locally.

**Comment by iarspider** [comment]
Should I open a separate issue for that one?

**Comment by vsoch** [comment]
For the spack issues? Sure thing - actually I can just go ahead and try to parse out my changes into a new PR for spack -I can ping you if you like.

**Comment by vsoch** [comment]
And I tested the build and was able to reproduce your error - the change is indeed Python jumping from 3.8 to 3.9 - how sneaky!

**Comment by vsoch** [comment]
lol! I totally already did this :laughing:  https://github.com/spack/spack/pull/27511

Nobody has looked at it though :shrug:

**Comment by iarspider** [comment]
> For the spack issues? 

No, for the missing import. Anyway, this is solved with #43, closing.

**Comment by vsoch** [comment]
Thank you for the fix!
